### ISSUE TITLE
Make all the Web Pages Responsive

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#106]
Home Page: @preethi0309 - Done
Login / Signup: @SravanthiRK -  Done
Projects / Events: @kimsuka -  Done
Eduation: @nithinmt21 - Done
Select Project / Event Page for Donation:  @nithinmt21  - Done
Donate Page (Actual donation page divided into 3 sections): @nithinmt21 - Done
Receipt Page: @SravanthiRK - Need to work on this. @sandeepyadavm to finish back end task.
Admin Portal: @SravanthiRK  - Done, Minor changes pending in Create Menu Mobile View.
About: @kimsuka - Done
Contact: @nithinmt21 - Done

**Comment by SravanthiRK** [comment]
@preethi0309 to work on following tasks:
1. Suggest section.  --Done
2. Carousals on Home page. -- Done
3. Add Login link on Sign up page & Sign up link on Login page. -- Done

**Comment by SravanthiRK** [comment]
@nithinmt21 to fix Credit card number issue.
