### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#116]
1. Open Charity Website.
2. Login with your your credentials.
3. Click on the Profile Tab user the Header Section.
4. Click on "Reset" button next to password. -> User gets redirected to Home Page.

**Ideally user should be redirected to Rest password page.**

**Comment by sandeepyadavm** [comment]
same issue as 20

**Comment by sandeepyadavm** [comment]
sorry, it is not same as 20, 

Anyway, this issue is fixed in current master
