### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by nithinmt21** [YogeshNaikZionTech/charityfoundation#123]

**Comment by sandeepyadavm** [comment]
1-send mail two days earlier for volunteering
2-send mail about monthly payment two days before the date
3-make payment.
4-remove all the deleted user images
5-change status of the project once completed
6-change status of the event once completed

**Comment by sandeepyadavm** [comment]
@ecaed099b527140049090132e098a715f4259cce

All cron job created.
