### ISSUE TITLE
Home Page: User Dropdown tabs

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#15]
Align the position of Logout & Profile section under the User Dropdown. Add new tab: Donation History. @sandeepyadavm

**Comment by sandeepyadavm** [comment]
Enhancement is completed in the following commit [https://github.com/YogeshNaikZionTech/charityfoundation/commit/a37288fc399dabc69dccb4a22873b91d99ee1fa7](url)
