### ISSUE TITLE
Home Page: Take of Top Donors. Change it to total number of Donations

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#16]
Take off Top Donors tab on Home page. Change it to Total number of Donations. @kimsuka

**Comment by kimsuka** [comment]
Removed Top Donor List - Didn't add total number.

**Comment by YogeshNaikZionTech** [comment]
Re-opened: Total Number of Donation Sections is missing on Home Page

**Comment by kimsuka** [comment]
Added Total Number of Donations
