### ISSUE TITLE
Welcome page layout is not data reponsive.

### ISSUE THREAD

**Issue by sandeepyadavm** [YogeshNaikZionTech/charityfoundation#19]
Current welcome page that we have does not accomodate the projects and events properly. I mean we have
- Competed -project and events
  *future - projects and events
- current - projects and events

From above,you can see that we have total of 6 unique items to show on the page and In that 6, we might again have many to show. So We have to decide  on how the page handles all the projects and event.

I made changes on [wlcome page](https://github.com/YogeshNaikZionTech/charityfoundation/blob/a37288fc399dabc69dccb4a22873b91d99ee1fa7/resources/views/welcome.blade.php) to work with the backend please have a look.
 @YogeshNaikZionTech  @nithinmt21

**Comment by YogeshNaikZionTech** [comment]
Saumya to fix this code.

**Comment by YogeshNaikZionTech** [comment]
Closing this issue as this does not exist now. Home page has been changed entirely.
