### ISSUE TITLE
Create event model appers but does not respond.

### ISSUE THREAD

**Issue by sandeepyadavm** [YogeshNaikZionTech/charityfoundation#20]
In this [show event page](https://github.com/YogeshNaikZionTech/charityfoundation/blob/a37288fc399dabc69dccb4a22873b91d99ee1fa7/resources/views/events/show.blade.php) for admin event creation model appears but on button click instead of performing the post action it dissmiss. Please look in to it to make sure it throws a post request on the action url.

**Comment by YogeshNaikZionTech** [comment]
@sandeepyadavm will work on this to fix the back end part.

**Comment by sandeepyadavm** [comment]
it working now.
