### ISSUE TITLE
Login / Sign up Links on Footer working incorrectly

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#38]
Logged in User clicks on Login/ Sign up link on the Footer. Error page is Shown. 

OR It User should remain on the existing page with a Massage " You are already Logged in".

@sandeepyadavm

**Comment by sandeepyadavm** [comment]
this is close as i removed the login and singup if user is loged in. 
Curently if user Loged than he would not see login and singup options.
