### ISSUE TITLE
Admin Page Create Projects / Events Section: Integrate with the backend

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#53]
Admin Page Create Projects / Events Page: Integrate with the backend

**Comment by YogeshNaikZionTech** [comment]
Sandeep: Please work on the back end part. Sravanthi is finished with the front end work.

**Comment by sandeepyadavm** [comment]
I am done with my part of storing all the event and  project in database but i find few fields are missing in Admin page:Event and project

**Comment by SravanthiRK** [comment]
Today, I don't get a chance to work on it. Hopefully, I will do it by tomorrow EOD.

Sent from my iPhone

On Oct 22, 2016, at 7:27 PM, sandeepyadavm <notifications@github.com<mailto:notifications@github.com>> wrote:

I am done with my part of storing all the event and project in database but i find few fields are missing in Admin page:Event and project

##
