### ISSUE TITLE
Rework on the Footer alignment 

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#80]
Spread 4 sections evenly on the top (Project/Events Section, login/Signup Section, Address Section, and The Social Media Section) get the Copyright text along with Privacy Policy & Terms links at the bottom evenly centered.

**Comment by YogeshNaikZionTech** [comment]
Reopening this issues as Discussed with Shravanti

**Comment by SravanthiRK** [comment]
Rework on Footer is done, Deleted login, signup, about us, contact us links from the footer as we have already have those in navbar, so made it simple
