### ISSUE TITLE
Emails & notifications:

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#95]
We need an email notification for following:
1. User Register.
2. User Donation
3. User Volunteering (X)
4. Reset Password
5. Forget Password
6. Event Reminder (X)
7. Project Progress (This needs to be added in future)
8. Subscribe / Unsubscribe(X)

**Comment by sandeepyadavm** [comment]
Except X all are done. 

for all X need some more time to finish
