### ISSUE TITLE
User should be able to redirect to Receipt page after Donation

### ISSUE THREAD

**Issue by YogeshNaikZionTech** [YogeshNaikZionTech/charityfoundation#98]
User should be able to redirect to Receipt page after Donation

**Comment by sandeepyadavm** [comment]
Update: user is redirected but on to a new tab on the browser. Should work to make the receipt page appear on the same tab as donation.

**Comment by sandeepyadavm** [comment]
This is fixed with the latest commit.

**Comment by YogeshNaikZionTech** [comment]
![donation receipt error](https://cloud.githubusercontent.com/assets/14792762/20505276/ae074f6c-b000-11e6-8fac-268766279592.png)
Tested this. User is redirected to a page which shows error. Screenshot attached,

**Comment by sandeepyadavm** [comment]
it is not fised with the new master
